# Generated by Django 5.1.5 on 2025-01-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0002_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='type',
            field=models.CharField(choices=[('type', 'Type'), ('provider', 'Provider')], default='customer', max_length=10),
        ),
    ]
