# Generated by Django 5.1.5 on 2025-02-15 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0009_userprofile_uploaded_at_alter_userprofile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='uploaded_at',
        ),
    ]
