# Generated by Django 5.1.5 on 2025-01-31 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_type',
            new_name='offer_type',
        ),
    ]
