# Generated by Django 5.1.5 on 2025-01-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0002_offer_created_at_offer_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='max_delivery_time',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
