# Generated by Django 5.1.5 on 2025-01-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0003_offer_max_delivery_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='max_delivery_time',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='min_delivery_time',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='min_price',
        ),
        migrations.RemoveField(
            model_name='offerdetail',
            name='url',
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='delivery_time_in_days',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='features',
            field=models.JSONField(default='default-feature'),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='offer_type',
            field=models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], default='basic', max_length=50),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='revisions',
            field=models.PositiveIntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='title',
            field=models.CharField(default='default-title', max_length=255),
        ),
        migrations.AlterField(
            model_name='offer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(default='default-title', max_length=255),
        ),
    ]
