# Generated by Django 5.1.5 on 2025-01-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0004_remove_offer_max_delivery_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
