# Generated by Django 5.1.5 on 2025-01-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0005_offer_min_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='min_delivery_time',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
