# Generated by Django 5.1.5 on 2025-02-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_count', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('business_profile_count', models.IntegerField(default=0)),
                ('offer_count', models.IntegerField(default=0)),
            ],
        ),
    ]
